name: Create File Workflow
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if group is running
        run: |
          if [ -f lock ]; then
            echo "Group is already running, exiting workflow."
            exit 0
          fi

      - name: Create file
        run: touch lock
        

      - name: Commit and push file
        env:
          ACCESS_TOKEN: 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
        run: |
          git config --local user.email "chennasai1@gmail.com"
          git config --local user.name "SaiChenna1"
          git add lock
          git commit -m "Add lock file"
          git push https://github.com/$GITHUB_REPOSITORY.git
          # HEAD:refs/heads/$GITHUB_REF
          
      
      - name: run the script
        run: sleep 50s

      # Rest of the workflow steps

      - name: Release shared resource
        run: |
          rm lock
