name: Create File Workflow
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file
        run: touch group.lock

      - name: Commit and push file
        env:
          ACCESS_TOKEN: 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
        run: |
          git config --local user.email "chennasai1@gmail.com"
          git config --local user.name "SaiChenna1"
          git add group.lock
          git commit -m "Add group.lock file"
          git push https://github.com/$GITHUB_REPOSITORY.git HEAD:refs/heads/$GITHUB_REF
