name: Create File Workflow
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
env:
      ACCESS_TOKEN: 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
jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if group is running
        id: check_lock
        run: |
          file_path="lock2"
          if [  -f "$file_path" ]; then
            echo "::set-output name=file_exists::true"
            else
            echo " ::set-output name=file_exists::false"
            fi
      - name: Use file existence status
        run: |
          file_exists=${{ steps.check_lock.outputs.file_exists }}

          if [ "$file_exists" == "true" ]; then
            echo "File exists!"
          else
            echo "File does not exist!"
          fi
      - name: create lock
        run: |
          if [ "$file_exists" == false ]
              touch lock2
              git config --local user.email "chennasai1@gmail.com"
              git config --local user.name "SaiChenna1"
              git add lock4
              git commit -m "Add lock2 file"
              git push https://github.com/$GITHUB_REPOSITORY.git
      - name: waiting 
        run: |
          if [ "$file_exists" == "true" ] 
              
               echo " waiting for previous workflow completed"
               sleep 10s
            
      - name: run the script
        run: sleep 50s

      # Rest of the workflow steps

      - name: Delete file
        run: |
          
          file_path="SaiChenna1/study/lock2"

          git rm "$file_path"
          git commit -m "Delete file $file_path"
          git push
          
          
#       - name: Create file
#         run: touch lock
        

#       - name: Commit and push file
#         env:
#           ACCESS_TOKEN: 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
#         run: |
#           git config --local user.email "chennasai1@gmail.com"
#           git config --local user.name "SaiChenna1"
#           git add lock2
#           git commit -m "Add lock2 file"
#           git push https://github.com/$GITHUB_REPOSITORY.git
#           # HEAD:refs/heads/$GITHUB_REF
          
      
      
