name: push_file
on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: file creating
        run: touch file2 ${{ github.workspace }}
        
      - name: Create Directory
        run: mkdir -p SaiChenna1/study/.github/workflows/files

      - name: Create File
        run: |
          echo "This is a test file." > SaiChenna1/study/.github/workflows/files/newfile.txt
      - name: Commit and Push Changes
        env:
         PAT_TOKEN: ${{ secrets.REPO_ACCESS_BETATOKEN }}
        run: |
          git config --global user.name "SaiChenna1"
          git config --global user.email "chennasai1@gmail.com"
          git add SaiChenna1/study/.github/workflows/files/newfile.txt
          git commit -m "Add new file"
          git remote set-url origin https://github.com/SaiChenna1/study
          git push origin HEAD
